### ISSUE TITLE
Error: goocanvasmm: "cxx11" is not a recognized standard

### ISSUE THREAD

**Issue by s1rleblanc** [wernerturing/homebrew-multi-delogo#1]
i am trying to install but had this error:

$ brew install wernerturing/multi-delogo/multi-delogo
Updating Homebrew...

==> Installing multi-delogo from wernerturing/multi-delogo
Error: goocanvasmm: "cxx11" is not a recognized standard

don't know what to do

**Comment by fuzunspm** [comment]
same issue

**Comment by wernerturing** [comment]
I removed the problematic line and it seems to be working now.
